apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 15.164.129.57:8090/container-platform/container-platform-api:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 3333
        env:
        - name: K8S_IP
          value: "172.16.10.214" 
        - name: CLUSTER_NAME
          value: "cp-cluster"
        - name: CONTAINER_PLATFORM_COMMON_API_URL
          value: "common-api-deployment.default.svc.cluster.local:3334"  
      imagePullSecrets:
        - name: jenkins-secret
      nodeSelector:
        kubernetes.io/hostname: paasta-cp-dev-cluster-2
---
apiVersion: v1
kind: Service
metadata:
  name: api-deployment
  labels:
    app: api
  namespace: default
spec:
  ports:
  - nodePort: 30333
    port: 3333
    protocol: TCP
    targetPort: 3333
  selector:
    app: api
  type: NodePort